### PR TITLE
Update email_lang.php

### PR DESCRIPTION
**Pull request by Mauricevb**
All Dutch translations are very bad and informal. It's all written like Codeigniter is a person. For example: "I can't.." instead of "Unable to". This commit is just the beginning. I think all other files have to be edited too.

### CODE REVIEW

**Comment by Razican** [comment]
Please, do not create tens of pull requests D: with one is enough.

**Comment by jim-parry** [comment]
@pkrul Do you concur?

**Comment by Mauricevb** [comment]
@Razican Excuse me, I did not understand how it works. Now I do :)

**Comment by jim-parry** [comment]
Incorporate this into PR #188 please, so all the proposed changes to the Dutch translation are together.

**Pull request closed without merging**
