### PR TITLE
Turkish translation

### PR DESCRIPTION
**Pull request by obozdag**
Turkish translation has been completed

### CODE REVIEW

**Comment by jim-parry** [comment]
One small change: could you change the footer comment from "system/language/english" to "application/language/turkish"? Other than that, looking good :)

**Comment by obozdag** [comment]
Changed footer comments to turkish. Also aligned tabs and converted them to spaces.

**Comment by jim-parry** [comment]
Almost there ... the footer comments should reference "application/language" and not "system/language", as these translations are intended to be a resorce for developers and not part of the "core" of CodeIgniter. Thanks :)

**Comment by obozdag** [comment]
Sorry, I missed application part. I hope it is ok now.

**Pull request merged**
