### PR TITLE
Master

### PR DESCRIPTION
**Pull request by rakheshthayyur**
Add new language Malayalam

### CODE REVIEW

**Comment by jim-parry** [comment]
Your description is off base, but this does highlight a branch merging issue, which I will fix.

**Comment by rakheshthayyur** [comment]
Please add folder for language 'malayalam', later i can upload the translated files

**Comment by jim-parry** [comment]
I will only add the folder once the translation PR is ready. I do not want empty language folders.

**Comment by rakheshthayyur** [comment]
@jim-parry ok, Let me prepare the translation files

**Pull request closed without merging**
