### PR TITLE
Update ftp_lang.php

### PR DESCRIPTION
**Pull request by Mauricevb**
Made it 'not childishly'

### CODE REVIEW

**Comment by jim-parry** [comment]
@pkrul Actually, there are a number of PRs from the same person for you to comment on.

**Comment by pkrul** [comment]
In the Dutch language, a sentence with "Kan" is incorrect. A correct example would be "Het systeem kan".

**Comment by Mauricevb** [comment]
I understand what you mean. But do you agree with me that it's better to use "het systeem" instead of "ik"? 
And to delete "ja? Dus.." etc.

**Comment by pkrul** [comment]
Yep, I agree. Those messages were inspired by the original files in English

**Comment by jim-parry** [comment]
@pkrul Does this mean that you are ok with all of the pull requests from @Mauricevb ?
Would it be easier to close all but one of the PRs and deal with adjustments in just that one?

**Comment by jim-parry** [comment]
I have asked that all the PRs be collected here, in just the one.
Once that is done, I will then be looking for Pieter Krul to approve/comment on the whole lot of changes :)

**Comment by Mauricevb** [comment]
@pkrul Can you please approve or comment on these changes?

**Comment by jim-parry** [comment]
@Mauricevb You need to add the other language file changes to this pull request - it is only for the one file at the moment.

**Comment by Mauricevb** [comment]
@jim-parry Actually I have no idea how to do this. So for now I will use these translations in my own projects. Maybe I will understand the 'GIT workflow' in the future so I can contribute the right way :)

**Comment by jim-parry** [comment]
Hmmm - I see that this pull request is from an unknown repository.
I suggest creating a new branch in your forked repo, and "git adding" each of the translation files to it, before creating a pull request.
Alternately, email the lot of them to me, and I can create a pull request for the group for you :)

**Comment by Razican** [comment]
The thing is that probably he used GitHub's online editor instead of doing it in his computer, with the "correct" workflow.

**Comment by Mauricevb** [comment]
That's right. I did use the online editor. I created a new pull request with the correct workflow: https://github.com/bcit-ci/codeigniter3-translations/pull/192 :)

**Pull request closed without merging**
