### PR TITLE
Updated 'form_validation_in_list' message #162

### PR DESCRIPTION
**Pull request by ridho1991**

### CODE REVIEW

**Comment by jim-parry** [comment]
Don't you love github? :)

**Comment by ridho1991** [comment]
I never use github before. :D, I just don't understand how github works.

**Comment by jim-parry** [comment]
You are not alone! https://www.atlassian.com/git/ has some simple tutorials :)
I am working on some too, but they are not ready yet.
Look at this as a learning opportunity!

**Comment by ridho1991** [comment]
thanks a lot.

**Pull request merged**
