### PR TITLE
added bengali translation

### PR DESCRIPTION
**Pull request by kabircse**

### CODE REVIEW

**Comment by kabircse** [comment]
@jim-parry

**Comment by jim-parry** [comment]
Hi fix your PR as follows...
readme.rst: the line with your translation needs to be in the proper place alphabetically, i.e. after azerbaijani; it's status should be 3.0.x, as it is not in the 3.0.4 release
changelog.rst: either leave that for me to change, or add a Version 3.0.x section at the top, with no release date, and showing bengali as a new translation

Thanks

**Comment by kabircse** [comment]
@jim-parry, I have updated my files.

**Comment by jim-parry** [comment]
Drop the readme and changelog entries from your PR, please - you are not "getting" them right, and I will add those myself.

**Comment by kabircse** [comment]
@jim-parry, I reverted readme and changelog files. Thanks.

**Pull request merged**
