### PR TITLE
Language files, Copyright update and typos correction for Portuguese

### PR DESCRIPTION
**Pull request by uilson**
- Updated the copyright to 2014-2020 and corrected some misspelled words.
- Updated files with need translations to match CodeIgniter 3.1-stable English files (also included 2 translations present in develop version, for future proof, that being the base64 and the webp messages)

Portuguese manager, does not maintain the Portuguese translation anymore. I am available to take the position..

### CODE REVIEW

**Comment by uilson** [comment]
Anyone?? Or is this repo not maintained anymore?

**Comment by uilson** [comment]
@j38600 como é isto ta morto ou que?

No one merges the corrections.. whats the point in helping the project?

**Review by j38600 — APPROVED** [review]

**Comment by j38600** [comment]
@uilson Queres ficar com o meu lugar neste repositório? Claramente não tenho tido tempo para ele...

**Comment by uilson** [comment]
@j38600 Se não te importares, posso ficar no teu lugar, uma vez que tenho um projeto a ser desenvolvido em CI (com planos a eventual passagem para a versão CI4).

Mais tarde se quiseres voltar dizes e voltas  para o teu lugar.

**Comment by uilson** [comment]
@narfbg can you approve the pull request?

by the way, the talk in portuguese between me and j38600 was he telling me that he didn't had time to keep this updated, and offering his place here to me.

I have a project in CI3 and plans to eventually move it to CI4, and don't mind becoming the new translator and doing the translations for Codeigniter in portuguese.

**Comment by narfbg** [comment]
Sorry about the delay. This was @jim-parry's domain and I never really paid attention to this repository.

I don't know @j38600 and I don't see him in the team members list, so while I don't mind you "replacing" him, I don't see a role to be replaced. Maybe @lonnieezell can step in with this decision.

**Pull request merged**
