### PR TITLE
Update date_lang.php

### PR DESCRIPTION
**Pull request by aelharrak**

### CODE REVIEW

**Comment by jim-parry** [comment]
@daif Do you concur?

**Comment by aelharrak** [comment]
yes

**Comment by jim-parry** [comment]
My "concurring" question was directed to the maintainer of this translation :-/

**Comment by daif** [comment]
@jim-parry  Yes
@aelharrak   Thank you

**Comment by aelharrak** [comment]
@daif Thank you and baraka allaho fik :)

**Pull request merged**
