### PR TITLE
[Fr] Fixes

### PR DESCRIPTION
**Pull request by FrozenWay**
Hello,

I'm a French-Italian student in an engineering school, web developer for 5 years and I use CI on my personal and professional projects.
I wanted to check the progression of the French translation and I noticed some tiny mistakes, so I figured I had to help you with that.

Here are the explanations for the fixes. They don't include typos (Accents, wrong letters). Some are debatable, and new ones can be found this way.

date_: 
- 42. The string is the same as the next one, so I linked both ;
- Aligned "=" chars ;
- Used the same quote format for each string (double) ;
- Aligned UTC hours for consistence purposes.

db_: 
- "fournir", "passer en paramètre", "indiquer" are sometimes better, contextually speaking, than "soumettre", which is usually employed for form submission ;
- "supporter" is better than "soumettre", when the meaning is related to feature support ;
- We don't say "colonne" that much in French, when talking about a table field. "Champ" is more accurate.

email_:
- In French typography, you have to put spaces before and after complex punctuation (colon, semicolon, exclamation mark, interrogation mark, etc.).

form_validation_:
- "Integer" is not user-friendly. "Nombre entier" is more likely to be understood.

migration_:
- Zero is considered singular. Plural forms are not justified here.

number_:
- French translation for [KMGT]B is [KMGT]o.

upload_:
- Talking about possibility is better than capability for a non-human/physical object.

Remember that these fixes are totally debatable, and my pull request is just a suggestion.

Thank you.
- Vincenzo S.

### CODE REVIEW

**Comment by jim-parry** [comment]
@includebeer Do you agree?

**Comment by includebeer** [comment]
Thanks for your help! I agree with most of your corrections. 

But, while it's valid PHP code, for me this looks like it's missing a translation:
```
$lang['date_month'] =
$lang['date_months'] = "Mois";
```

Also, for the timezone, we should remove the space after the + and - signs, like in the original english text. Example:
```
(UTC - 12:00) Îles Baker / Howland (french translation)
(UTC -12:00) Baker/Howland Island (original english text)
```

**Comment by includebeer** [comment]
I was in the Christmas rush when I submited my translations, so a didn't notice all those typos / mistakes. But now I have some time off, so if you don't have time to fix the timezones, I can do it. Thanks again for your help! :)

**Comment by FrozenWay** [comment]
About the timezones, I thought it was an odd translation typo. And for date_, I completely agree with you, and the optimization is quite poor, actually.

I just checked the files twice, so I guess I should check them again to find more potential mistakes. I will commit that later today :)

**Comment by includebeer** [comment]
Awsome!

**Comment by FrozenWay** [comment]
Now, that should be better.
The spaces are removed according to the original format, date_month is fixed.

I added a capital to the cardinal directions ("Est", "Ouest", etc.) that were missing one, and fixed two typos on email_.

**Comment by includebeer** [comment]
@FrozenWay Excellent, thank you!
@jim-parry This PR has my seal of approval! ;)

**Pull request merged**
