### PR TITLE
Add Indonesian Translation

### PR DESCRIPTION
**Pull request by ridho1991**
Add Indonesian Translation

### CODE REVIEW

**Comment by jim-parry** [comment]
The footer comment should read "application/language" and not "system/language".
Other than that, looking good :)
Don't forget to "sign" your git commits!

**Comment by jim-parry** [comment]
ps Wouldn't the idiom be "indonesian" rather than "indonesia"?

**Comment by ridho1991** [comment]
I already fixed it.

**Comment by jim-parry** [comment]
Excellent, thanks!

**Pull request merged**
