### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by atefBB**

### CODE REVIEW

**Comment by jim-parry** [comment]
Is there a reason for seven PRs (so far), each modifying a fews lines in one file?
Can these be consolidated into one?
Thanks

**Comment by atefBB** [comment]
how can I do that?
Excuse me !

**Comment by jim-parry** [comment]
Instead of creating a new PR for each file's corrections, as long as you are working in the same feature branch, you can just push them to your repo, and they will get added to the PR automatically.

**Comment by atefBB** [comment]
Thanks ! 
Ahha ! I'll consider your advice in the future PRs ! ^___^

**Comment by jim-parry** [comment]
@ihab-mardoud You are not the maintainer for this translation?
@daif Do you concur with the change(s)?

**Pull request merged**
