### PR TITLE
Fixes two misspelled words

### PR DESCRIPTION
**Pull request by alextegelid**

### CODE REVIEW

**Comment by alextegelid** [comment]
Sorry... Didn't read the info about contributing

**Comment by jim-parry** [comment]
@peterdenk What do you think of the mis-spellings?

**Comment by peterdenk** [comment]
Certainly mis-spellings!
Thanks for spotting them @alextegelid.

**Comment by alextegelid** [comment]
No problem, happy to help! I'll re-open this :)

**Pull request merged**
