### PR TITLE
Abbreviations changed in accordance with national standard

### PR DESCRIPTION
**Pull request by shlangus**
Abbreviations changed in accordance with national standard GOST 8.417-2002 (ГОСТ 8.417-2002)

### CODE REVIEW

**Comment by jim-parry** [comment]
@vadimyer Do you concur with this?

**Comment by jim-parry** [comment]
Oops - I committed accidentally, sorry. I will recommit if you concur with the changes!

**Comment by vadimyer** [comment]
@jim-parry Yes, it's correct.

**Comment by jim-parry** [comment]
Ok, thanks  :)

**Pull request merged**
