### PR TITLE
Update form_validation_lang.php

### PR DESCRIPTION
**Pull request by sobhanattar**
Do some correction on translations

### CODE REVIEW

**Comment by jim-parry** [comment]
If you are planning changes to multiple language files, please consolidate them into one pull request. That will make it easier for the maintainer to approve/comment on them.
I will let this one stand, but if there are more, group them into #249.
Thanks!

@MSDehghan Do you concur with these changes?

**Comment by sobhanattar** [comment]
@jim-parry thanks for your attention, I'm not so familiar with this platform which has been resulted in making mistake by creating different branches for one general purpose.
I did some editing on ftp_lang file and commit it to patch-2 which is equal to #249. I hope i did it right :)

**Comment by jim-parry** [comment]
Much easier to work with, thanks :)

**Comment by MSDehghan** [comment]
it's ok

**Pull request merged**
